// Generated by CoffeeScript 1.9.1
(function() {
  var coffee_mate,
    slice = [].slice;

  coffee_mate = (function() {
    var Y, abs, accept_multi_or_array, all, any, assert, assertEq, assertEqOn, best, bool, cartProd, ceil, chr, church, concat, copy, cube, deepcopy, dict, drop, dropWhile, enumerate, filter, float, floor, foldl, foreach, function_literal, hex, int, iter_brk, iter_end, iterate, iterator, json, last, list, log, map, max, max_index, memoize, min, min_index, nature_number, new_iterator, next_permutation, obj, ord, permutation_gen, pretty_iterator, prime_number, random_gen, range, ranged_random_gen, ref, reverse, scanl, securely, show_iter, square, str, streak, sum, take, takeWhile, time_now, uri_decoder, uri_encoder, zip;
    function_literal = function(f) {
      var expr;
      expr = f.toString().replace(/^\s*function\s?\(\s?\)\s?{\s*return\s*([^]*?);?\s*}$/, '$1');
      if (expr.length <= 100) {
        expr = expr.replace(/[\r\n]{1,2}\s*/g, '');
      }
      return expr;
    };
    time_now = function() {
      return (new Date).getTime();
    };
    log = (function() {
      var dye, factory, got, histories, log_label;
      dye = (function() {
        var cavailable, palette;
        cavailable = (typeof process !== "undefined" && process !== null) && !process.env.NODE_DISABLE_COLORS;
        palette = {
          bold: '\x1B[0;1m',
          red: '\x1B[0;31m',
          green: '\x1B[0;32m',
          yellow: '\x1B[0;33m',
          blue: '\x1B[0;34m',
          bold_grey: '\x1B[1;30m'
        };
        if (!cavailable) {
          return function(color) {
            return function(s) {
              return s;
            };
          };
        } else {
          return function(color) {
            return function(s) {
              return "" + palette[color] + s + '\x1B[0m';
            };
          };
        }
      })();
      log_label = (function() {
        var flag_palette, op_flag;
        flag_palette = {
          '#': 'bold_grey',
          'I': 'green',
          'E': 'red',
          'W': 'yellow'
        };
        op_flag = function(op) {
          if (op === 'log') {
            return '#';
          } else {
            return op[0].toUpperCase();
          }
        };
        return function(op) {
          var flag;
          flag = op_flag(op);
          return dye(flag_palette[flag])(flag);
        };
      })();
      histories = [];
      factory = function(op) {
        var prefix;
        prefix = "" + (dye('bold_grey')('#')) + (log_label(op));
        return function() {
          var args, ball, eval_result, expr, f, len1, o, start_time, time_used;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          ball = [];
          for (o = 0, len1 = args.length; o < len1; o++) {
            f = args[o];
            if (typeof f === 'function') {
              expr = function_literal(f);
              start_time = time_now();
              eval_result = f();
              time_used = time_now() - start_time;
              ball.push(prefix + " " + (dye('green')(expr)) + " " + (dye('bold_grey')('==>')), f());
              if (time_used > 0) {
                ball.push(dye('yellow')("[" + time_used + "ms]"));
              }
            } else {
              ball.push("" + prefix, f);
            }
          }
          console[op].apply(console, ball);
          histories.push(ball);
          if (histories.length >= 10) {
            histories.shift();
          }
          return null;
        };
      };
      got = factory('log');
      got.histories = histories;
      got.info = factory('info');
      got.warn = factory('warn');
      got.error = got.err = factory('error');
      return got;
    })();
    assert = function(f, msg) {
      var e, ref;
      if (!(f instanceof Function)) {
        ref = [msg, f], f = ref[0], msg = ref[1];
      }
      try {
        if (!f()) {
          throw Error("Assertion " + (msg != null ? msg : function_literal(f)) + " Failed!");
        }
      } catch (_error) {
        e = _error;
        throw Error("Assertion " + (msg != null ? msg : function_literal(f)) + " Unknown:\n" + e);
      }
    };
    assertEq = function(l, r) {
      var e, lv, rv;
      try {
        lv = l();
        rv = r();
      } catch (_error) {
        e = _error;
        throw Error("Equation Between " + (function_literal(l)) + " And " + (function_literal(r)) + " Unknown:\n" + e);
      }
      if (lv !== rv) {
        throw Error("Equation Failed:\n\t" + (function_literal(l)) + " IS " + lv + " BUT\n\t" + (function_literal(r)) + " IS " + rv + ".");
      }
    };
    assertEqOn = function(f) {
      return function(l, r) {
        var e, flv, frv, lv, rv;
        try {
          lv = l();
          rv = r();
          flv = f(lv);
          frv = f(rv);
        } catch (_error) {
          e = _error;
          throw Error("MAPPED Equation Between " + (function_literal(l)) + " And " + (function_literal(r)) + " Unknown:\n" + e);
        }
        if (flv !== frv) {
          throw Error("Equation Failed:\n\t" + (function_literal(l)) + " IS " + lv + " AND MAPPED TO " + flv + " BUT\n\t" + (function_literal(r)) + " IS " + rv + " AND MAPPED TO " + frv + ".");
        }
      };
    };
    securely = function(f) {
      return function() {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        args = deepcopy(args);
        return f.apply(null, args);
      };
    };
    dict = function(pairs) {
      var d, k, len1, o, ref, v;
      d = {};
      for (o = 0, len1 = pairs.length; o < len1; o++) {
        ref = pairs[o], k = ref[0], v = ref[1];
        d[k] = v;
      }
      return d;
    };
    ref = (function() {
      var cp;
      cp = function(root, dep) {
        var k, r, v;
        if (dep === 0 || (root == null) || typeof root !== 'object') {
          return root;
        }
        if (root instanceof Array) {
          r = (function() {
            var len1, o, results;
            results = [];
            for (o = 0, len1 = root.length; o < len1; o++) {
              v = root[o];
              results.push(cp(v, dep - 1));
            }
            return results;
          })();
        } else {
          r = {};
          for (k in root) {
            v = root[k];
            r[k] = cp(v, dep - 1);
          }
        }
        return r;
      };
      return {
        copy: function(obj, depth) {
          if (depth == null) {
            depth = 1;
          }
          return cp(obj, depth);
        },
        deepcopy: function(obj, depth) {
          if (depth == null) {
            depth = Infinity;
          }
          return cp(obj, depth);
        }
      };
    })(), copy = ref.copy, deepcopy = ref.deepcopy;
    int = function(s, base) {
      var r;
      if (typeof s === 'string') {
        r = parseInt(s, base);
        if (!((s.slice != null) && r === parseInt(s.slice(0, -1), base))) {
          return r;
        } else {
          return null;
        }
      } else {
        return parseInt(0 + s);
      }
    };
    float = function(s) {
      if (/^-?[0-9]*(\.[0-9]+)?([eE]-?[0-9]+)?$/.test(s)) {
        return parseFloat(s);
      } else {
        return null;
      }
    };
    str = function(x, base) {
      return x.toString(base);
    };
    bool = function(x) {
      if (x === true || x === false) {
        return x;
      } else {
        return null;
      }
    };
    hex = function(x) {
      return x.toString(16);
    };
    ord = function(c) {
      return c.charCodeAt();
    };
    chr = function(x) {
      return String.fromCharCode(x);
    };
    json = function(it, indent) {
      return JSON.stringify(it, null, indent);
    };
    obj = function(s) {
      return JSON.parse(s);
    };
    Object.defineProperties(String.prototype, {
      format: {
        enumerable: false,
        value: function(args) {
          return this.replace(/\{(\w+)\}/g, function(m, i) {
            if (args[i] != null) {
              return args[i];
            } else {
              return m;
            }
          });
        }
      },
      repeat: {
        enumerable: false,
        value: function(n) {
          var pat, r, ref1;
          ref1 = ['', this], r = ref1[0], pat = ref1[1];
          while (n > 0) {
            if (n & 1) {
              r += pat;
            }
            n >>= 1;
            pat += pat;
          }
          return r;
        }
      },
      cut: {
        enumerable: false,
        value: function(start_pat, end_pat) {
          var i, j;
          i = this.search(start_pat) + 1;
          if (i === 0) {
            return null;
          }
          j = this.substr(i).search(end_pat);
          if (j === -1) {
            return null;
          }
          return this.substr(i, j);
        }
      }
    });
    Object.defineProperties(Array.prototype, {
      first: {
        get: function() {
          return this[0];
        },
        set: function(v) {
          return this[0] = v;
        }
      },
      second: {
        get: function() {
          return this[1];
        },
        set: function(v) {
          return this[1] = v;
        }
      },
      third: {
        get: function() {
          return this[2];
        },
        set: function(v) {
          return this[2] = v;
        }
      },
      last: {
        get: function() {
          return this[this.length - 1];
        },
        set: function(v) {
          return this[this.length - 1] = v;
        }
      },
      repeat: {
        enumerable: false,
        value: function(n) {
          var pat, r, ref1;
          ref1 = [[], this], r = ref1[0], pat = ref1[1];
          while (n > 0) {
            if (n & 1) {
              r = r.concat(pat);
            }
            n >>= 1;
            pat = pat.concat(pat);
          }
          return r;
        }
      },
      unique: {
        enumerable: false,
        value: (function() {
          var init;
          init = new Object;
          return function(equal) {
            var i, j, len1, len2, o, q, t, x;
            i = 0;
            t = init;
            if (equal == null) {
              for (j = o = 0, len1 = this.length; o < len1; j = ++o) {
                x = this[j];
                if (!(x !== t)) {
                  continue;
                }
                this[i] = t = x;
                i += 1;
              }
            } else {
              for (j = q = 0, len2 = this.length; q < len2; j = ++q) {
                x = this[j];
                if (!(t === init || !equal(x, t))) {
                  continue;
                }
                this[i] = t = x;
                i += 1;
              }
            }
            this.splice(i, Infinity);
            return this;
          };
        })()
      }
    });
    Object.defineProperties(Object, {
      size: {
        enumerable: false,
        value: function(d) {
          return Object.keys(d).length;
        }
      },
      extend: {
        enumerable: false,
        value: function() {
          var base, d, defaults, k, len1, o, v;
          base = arguments[0], defaults = 2 <= arguments.length ? slice.call(arguments, 1) : [];
          for (o = 0, len1 = defaults.length; o < len1; o++) {
            d = defaults[o];
            if (d != null) {
              for (k in d) {
                v = d[k];
                if (base[k] == null) {
                  base[k] = v;
                }
              }
            }
          }
          return base;
        }
      },
      update: {
        enumerable: false,
        value: function() {
          var base, d, k, len1, o, updates, v;
          base = arguments[0], updates = 2 <= arguments.length ? slice.call(arguments, 1) : [];
          for (o = 0, len1 = updates.length; o < len1; o++) {
            d = updates[o];
            if (d != null) {
              for (k in d) {
                v = d[k];
                base[k] = v;
              }
            }
          }
          return base;
        }
      }
    });
    uri_encoder = function(component_packer) {
      if (component_packer == null) {
        component_packer = str;
      }
      return function(obj) {
        var k, v;
        return ((function() {
          var results;
          results = [];
          for (k in obj) {
            v = obj[k];
            results.push((encodeURIComponent(k)) + "=" + (encodeURIComponent(component_packer(v))));
          }
          return results;
        })()).join('&');
      };
    };
    uri_decoder = function(component_unpacker) {
      if (component_unpacker == null) {
        component_unpacker = (function(s) {
          return s;
        });
      }
      return function(str) {
        var d, k, len1, o, q, ref1, ref2, ref3, s, v;
        d = {};
        ref2 = (ref1 = str.match(/[^?=&]+=[^&]*/g)) != null ? ref1 : [];
        for (o = 0, len1 = ref2.length; o < len1; o++) {
          s = ref2[o];
          ref3 = s.match(/([^=]+)=(.*)/), q = ref3.length - 2, k = ref3[q++], v = ref3[q++];
          d[decodeURIComponent(k)] = component_unpacker(decodeURIComponent(v));
        }
        return d;
      };
    };
    random_gen = (function() {
      var hash;
      hash = function(x) {
        x = Math.sin(x) * 1e4;
        return x - Math.floor(x);
      };
      return function(seed) {
        var cnt;
        if (seed == null) {
          seed = Math.random();
        }
        cnt = hash(seed);
        return function() {
          return hash(++cnt);
        };
      };
    })();
    ranged_random_gen = function(range, seed) {
      var random;
      if (seed == null) {
        seed = Math.random();
      }
      random = random_gen(seed);
      return function() {
        return Math.floor(random() * range);
      };
    };
    iter_end = new Object;
    iter_brk = new Object;
    pretty_iterator = function(show, it) {
      it.toString = show;
      it.next = function() {
        var r;
        r = it();
        return {
          value: r,
          done: r === iter_end
        };
      };
      return it;
    };
    new_iterator = function(init, next) {
      var status;
      status = init;
      return pretty_iterator((function() {
        return "Iterator: " + (json(status)) + " ...";
      }), function() {
        var last;
        last = status;
        status = next(status);
        return last;
      });
    };
    show_iter = function(it) {
      var s;
      s = it.toString();
      if (it.next != null) {
        if (s.startsWith('function')) {
          return 'Iterator';
        } else {
          return s;
        }
      } else {
        return '???';
      }
    };
    nature_number = function(first) {
      var i;
      if (first == null) {
        first = 0;
      }
      i = first - 1;
      return pretty_iterator((function() {
        return "Counter: " + (i + 1) + ", " + (i + 2) + " ...";
      }), function() {
        return ++i;
      });
    };
    range = function() {
      var args, i, start, step, stop;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      if (args.length === 0) {
        return nature_number();
      } else if (args.length === 1) {
        stop = args[0];
        i = -1;
        return pretty_iterator((function() {
          return "Counter: " + (i + 1) + ", " + (i + 2) + " until " + stop;
        }), function() {
          if (++i < stop) {
            return i;
          } else {
            return iter_end;
          }
        });
      } else if (args.length === 2) {
        start = args[0], stop = args[1];
        if (start < stop) {
          i = start - 1;
          return pretty_iterator((function() {
            return "Counter: " + (i + 1) + ", " + (i + 2) + " until " + stop;
          }), function() {
            if (++i < stop) {
              return i;
            } else {
              return iter_end;
            }
          });
        } else {
          i = start + 1;
          return pretty_iterator((function() {
            return "Counter: " + (i - 1) + ", " + (i - 2) + " until " + stop;
          }), function() {
            if (--i > stop) {
              return i;
            } else {
              return iter_end;
            }
          });
        }
      } else {
        start = args[0], stop = args[1], step = args[2];
        if (stop !== start && (stop - start) * step < 0) {
          throw 'ERR IN range(): YOU ARE CREATING AN UNLIMITTED RANGE';
        }
        i = start - step;
        if (start < stop) {
          return pretty_iterator((function() {
            return "Counter: " + (i + step) + ", " + (i + step + step) + " until " + stop;
          }), function() {
            if ((i += step) < stop) {
              return i;
            } else {
              return iter_end;
            }
          });
        } else {
          return pretty_iterator((function() {
            return "Counter: " + (i + step) + ", " + (i + step + step) + " until " + stop;
          }), function() {
            if ((i += step) > stop) {
              return i;
            } else {
              return iter_end;
            }
          });
        }
      }
    };
    prime_number = function() {
      return filter(function(x) {
        return all(function(p) {
          return x % p !== 0;
        })(takeWhile(function(p) {
          return p * p <= x;
        })(range(2, Infinity)));
      })(range(2, Infinity));
    };
    next_permutation = function(x) {
      var l, m, r, ref1, ref2;
      l = x.length - 1;
      while (l >= 1 && x[l] <= x[l - 1]) {
        l--;
      }
      if (l !== 0) {
        m = x.length - 1;
        while (m > l - 1 && x[m] <= x[l - 1]) {
          m--;
        }
        ref1 = [x[l - 1], x[m]], x[m] = ref1[0], x[l - 1] = ref1[1];
      }
      r = x.length - 1;
      while (l < r) {
        ref2 = [x[r], x[l]], x[l] = ref2[0], x[r] = ref2[1];
        l++;
        r--;
      }
      return x;
    };
    permutation_gen = function(arr) {
      var a;
      a = function() {
        return new_iterator(arr, securely(next_permutation));
      };
      return concat([copy(arr)], takeWhile(function(ls) {
        return json(ls) !== json(arr);
      })(drop(1)(a())));
    };
    iterate = function(ls, replaced_end) {
      var i;
      i = -1;
      return pretty_iterator((function() {
        return "Enumerator: " + (ls.join(', '));
      }), function() {
        i += 1;
        if (i < ls.length) {
          if (ls[i] === iter_end) {
            if (replaced_end == null) {
              throw 'ERR IN iterate(): iterate.done APPEARS IN Array, PASS A SECOND ARG FOR REPLACEMENT';
            }
            return replaced_end;
          } else {
            return ls[i];
          }
        } else {
          return iter_end;
        }
      });
    };
    iterator = function(iterable, replaced_end) {
      if (typeof iterable === 'function') {
        return iterable;
      } else {
        if (!(iterable instanceof Array)) {
          throw 'ERR IN iterator(): ONLY Array & Iterator IS ACCEPTABLE';
        }
        return iterate(iterable, replaced_end);
      }
    };
    Object.defineProperties(iterator, {
      end: {
        writable: false,
        configurable: false,
        enumerable: false,
        value: iter_end
      }
    });
    enumerate = function(it, replaced_end) {
      var i, keys;
      if (typeof it === 'function') {
        return zip((function() {
          var i;
          i = -1;
          return function() {
            return ++i;
          };
        })(), it);
      } else if (it instanceof Array) {
        return zip((function() {
          var i;
          i = -1;
          return function() {
            return ++i;
          };
        })(), it);
      } else {
        keys = Object.keys(it);
        i = -1;
        return pretty_iterator((function() {
          var k, v;
          return "Enumerator: " + (((function() {
            var results;
            results = [];
            for (k in it) {
              v = it[k];
              results.push("[" + k + "," + v + "]");
            }
            return results;
          })()).join(', '));
        }), function() {
          var k;
          if (++i < keys.length) {
            return [(k = keys[i]), it[k]];
          } else {
            return iter_end;
          }
        });
      }
    };
    take = function(n) {
      if (typeof n === 'number') {
        return function(iter) {
          var c;
          iter = iterator(iter);
          c = -1;
          return pretty_iterator((function() {
            return "take(" + n + ") " + (show_iter(iter));
          }), function() {
            if (++c < n) {
              return iter();
            } else {
              return iter_end;
            }
          });
        };
      } else {
        return takeWhile(n);
      }
    };
    takeWhile = function(ok) {
      return function(iter) {
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        return pretty_iterator((function() {
          return "takeWhile(...) " + (show_iter(iter));
        }), function() {
          var x;
          if ((x = iter()) !== iter_end && ok(x)) {
            return x;
          } else {
            return iter_end;
          }
        });
      };
    };
    drop = function(n) {
      if (typeof n === 'number') {
        return function(iter) {
          var finished, i, o, ref1;
          if (typeof iter !== 'function') {
            iter = iterator(iter);
          }
          finished = false;
          for (i = o = 0, ref1 = n; 0 <= ref1 ? o < ref1 : o > ref1; i = 0 <= ref1 ? ++o : --o) {
            finished || (finished = iter() === iter_end);
            if (finished) {
              break;
            }
          }
          if (finished) {
            return function() {
              return iter_end;
            };
          } else {
            return iter;
          }
        };
      } else {
        return dropWhile(n);
      }
    };
    dropWhile = function(ok) {
      return function(iter) {
        var x;
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        while (ok(x = iter()) && x !== iter_end) {
          null;
        }
        return pretty_iterator((function() {
          return "dropWhile(...) " + (show_iter(iter));
        }), function() {
          var prevx, ref1;
          ref1 = [x, iter()], prevx = ref1[0], x = ref1[1];
          return prevx;
        });
      };
    };
    map = function(f) {
      return function(iter) {
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        return pretty_iterator((function() {
          return "map(...) " + (show_iter(iter));
        }), function() {
          var x;
          if ((x = iter()) !== iter_end) {
            return f(x);
          } else {
            return iter_end;
          }
        });
      };
    };
    filter = function(ok) {
      return function(iter) {
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        return pretty_iterator((function() {
          return "filter(...) " + (show_iter(iter));
        }), function() {
          var x;
          while (!ok(x = iter()) && x !== iter_end) {
            null;
          }
          return x;
        });
      };
    };
    scanl = function(f, r) {
      return function(iter) {
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        return pretty_iterator((function() {
          return "scanl(...) " + (show_iter(iter));
        }), function() {
          var got, x;
          got = r;
          r = (x = iter()) !== iter_end ? f(r, x) : iter_end;
          return got;
        });
      };
    };
    streak = function(n) {
      return function(iter) {
        var buf;
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        buf = [];
        return pretty_iterator((function() {
          return "streak(" + n + ") " + (show_iter(iter));
        }), function() {
          var x;
          if ((x = iter()) === iter_end) {
            return iter_end;
          }
          buf.push(x);
          if (buf.length > n) {
            buf.shift(1);
          }
          return buf.slice(0);
        });
      };
    };
    reverse = function(iter) {
      var ls;
      ls = typeof iter === 'function' ? list(iter) : copy(iter);
      return iterator(ls.reverse());
    };
    concat = function() {
      var current_index, i, iter, iters, len1, o, ref1;
      iters = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      for (i = o = 0, len1 = iters.length; o < len1; i = ++o) {
        iter = iters[i];
        if (typeof iter !== 'function') {
          iters[i] = iterator(iter);
        }
      }
      ref1 = [iters[0], 0], iter = ref1[0], current_index = ref1[1];
      return pretty_iterator((function() {
        var it;
        return "concat " + (((function() {
          var len2, q, results;
          results = [];
          for (q = 0, len2 = iters.length; q < len2; q++) {
            it = iters[q];
            results.push(show_iter(it));
          }
          return results;
        })()).join(', '));
      }), function() {
        var x;
        if ((x = iter()) !== iter_end) {
          return x;
        } else if (++current_index < iters.length) {
          iter = iters[current_index];
          return iter();
        } else {
          return iter_end;
        }
      });
    };
    zip = function() {
      var finished, i, iter, iters, len1, o;
      iters = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      for (i = o = 0, len1 = iters.length; o < len1; i = ++o) {
        iter = iters[i];
        if (typeof iter !== 'function') {
          iters[i] = iterator(iter);
        }
      }
      finished = (function() {
        var another_end, any_is_end;
        another_end = new Object;
        any_is_end = any(function(x) {
          return x === another_end;
        });
        return function(ls) {
          return any_is_end(iterator(ls, another_end));
        };
      })();
      return pretty_iterator((function() {
        var it;
        return "zip " + (((function() {
          var len2, q, results;
          results = [];
          for (q = 0, len2 = iters.length; q < len2; q++) {
            it = iters[q];
            results.push(show_iter(it));
          }
          return results;
        })()).join(', '));
      }), function() {
        var next;
        next = (function() {
          var len2, q, results;
          results = [];
          for (q = 0, len2 = iters.length; q < len2; q++) {
            iter = iters[q];
            results.push(iter());
          }
          return results;
        })();
        if (finished(next)) {
          return iter_end;
        } else {
          return next;
        }
      });
    };
    cartProd = (function() {
      var apply_vector, inc_vector;
      inc_vector = function(limits) {
        var len_minus_1;
        len_minus_1 = limits.length - 1;
        return function(vec) {
          var i;
          i = len_minus_1;
          while (!(++vec[i] < limits[i] || i <= 0)) {
            vec[i--] = 0;
          }
          return vec;
        };
      };
      apply_vector = function(space) {
        var len;
        len = space.length;
        return function(vec) {
          var i, o, ref1, results;
          results = [];
          for (i = o = 0, ref1 = len; 0 <= ref1 ? o < ref1 : o > ref1; i = 0 <= ref1 ? ++o : --o) {
            results.push(space[i][vec[i]]);
          }
          return results;
        };
      };
      return function() {
        var get_value, i, inc, iters, limits, set, sets, v;
        iters = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        sets = (function() {
          var len1, o, results;
          results = [];
          for (o = 0, len1 = iters.length; o < len1; o++) {
            set = iters[o];
            results.push(list(set));
          }
          return results;
        })();
        limits = (function() {
          var o, ref1, results;
          results = [];
          for (i = o = 0, ref1 = sets.length; 0 <= ref1 ? o < ref1 : o > ref1; i = 0 <= ref1 ? ++o : --o) {
            results.push(sets[i].length);
          }
          return results;
        })();
        inc = inc_vector(limits);
        get_value = apply_vector(sets);
        v = (function() {
          var o, ref1, results;
          results = [];
          for (i = o = 0, ref1 = sets.length; 0 <= ref1 ? o < ref1 : o > ref1; i = 0 <= ref1 ? ++o : --o) {
            results.push(0);
          }
          return results;
        })();
        return pretty_iterator((function() {
          var it;
          return "cartProd " + (((function() {
            var len1, o, results;
            results = [];
            for (o = 0, len1 = iters.length; o < len1; o++) {
              it = iters[o];
              results.push(show_iter(it));
            }
            return results;
          })()).join(', '));
        }), function() {
          var r;
          if (v[0] < limits[0]) {
            r = get_value(v);
            inc(v);
            return r;
          } else {
            return iter_end;
          }
        });
      };
    })();
    list = function(it) {
      var results, x;
      if (typeof it !== 'function') {
        return it;
      }
      results = [];
      while ((x = it()) !== iter_end) {
        results.push(x);
      }
      return results;
    };
    foreach = function(iter, callback, fruit) {
      var x;
      if (typeof iter !== 'function') {
        iter = iterator(iter);
      }
      while ((x = iter()) !== iter_end) {
        if (callback(x, fruit) === iter_brk) {
          break;
        }
      }
      return fruit;
    };
    Object.defineProperties(foreach, {
      "break": {
        writable: false,
        configurable: false,
        enumerable: false,
        value: iter_brk
      }
    });
    foldl = function(f, r) {
      return function(iter) {
        var x;
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        while ((x = iter()) !== iter_end) {
          r = f(r, x);
        }
        return r;
      };
    };
    best = function(better) {
      return function(iter) {
        var it, r;
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        if ((r = iter()) === iter_end) {
          return null;
        }
        while ((it = iter()) !== iter_end) {
          r = better(it, r) ? it : r;
        }
        return r;
      };
    };
    all = function(f) {
      if (typeof f !== 'function') {
        f = (function(x) {
          return x === f;
        });
      }
      return function(iter) {
        var x;
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        while ((x = iter()) !== iter_end) {
          if (!f(x)) {
            return false;
          }
        }
        return true;
      };
    };
    any = function(f) {
      var all_not;
      all_not = all(function(x) {
        return !f(x);
      });
      return function(iter) {
        return !(all_not(iter));
      };
    };
    last = function(iter, empty_sign) {
      var r, x;
      if (typeof iter !== 'function') {
        iter = iterator(iter);
      }
      r = empty_sign;
      while ((x = iter()) !== iter_end) {
        r = x;
      }
      return r;
    };
    church = function(n) {
      var iter;
      iter = function(f, n, r) {
        if (n === 0) {
          return r;
        } else {
          return iter(f, n - 1, f(r));
        }
      };
      return function(f) {
        return function(x) {
          return iter(f, n + 0, x);
        };
      };
    };
    Y = function(f) {
      return (function(x) {
        return x(x);
      })((function(x) {
        return f((function(y) {
          return (x(x))(y);
        }));
      }));
    };
    memoize = function(f, get_key) {
      var cache;
      if (get_key == null) {
        get_key = (function() {
          var args;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          return json(args);
        });
      }
      cache = {};
      return function() {
        var args, cached, key, r;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        key = get_key.apply(null, args);
        cached = cache[key];
        if (cached != null) {
          return cached;
        } else {
          r = f.apply(null, args);
          cache[key] = r;
          return r;
        }
      };
    };
    square = function(n) {
      return n * n;
    };
    cube = function(n) {
      return n * n * n;
    };
    abs = Math.abs;
    floor = Math.floor;
    ceil = Math.ceil;
    accept_multi_or_array = function(f) {
      return function() {
        var arr;
        arr = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return f(arr.length === 1 && arr.first instanceof Array ? arr.first : arr);
      };
    };
    sum = accept_multi_or_array(function(arr) {
      var len1, o, r, x;
      if (arr.length === 1 && arr.first instanceof Array) {
        arr = arr.first;
      }
      r = 0;
      for (o = 0, len1 = arr.length; o < len1; o++) {
        x = arr[o];
        r += x;
      }
      return r;
    });
    max = accept_multi_or_array(function(arr) {
      return best(function(a, b) {
        return a > b;
      })(arr);
    });
    min = accept_multi_or_array(function(arr) {
      return best(function(a, b) {
        return a < b;
      })(arr);
    });
    max_index = accept_multi_or_array(function(arr) {
      var o, ref1, results;
      return best(function(i, j) {
        return arr[i] > arr[j];
      })((function() {
        results = [];
        for (var o = 0, ref1 = arr.length; 0 <= ref1 ? o < ref1 : o > ref1; 0 <= ref1 ? o++ : o--){ results.push(o); }
        return results;
      }).apply(this));
    });
    min_index = accept_multi_or_array(function(arr) {
      var o, ref1, results;
      return best(function(i, j) {
        return arr[i] < arr[j];
      })((function() {
        results = [];
        for (var o = 0, ref1 = arr.length; 0 <= ref1 ? o < ref1 : o > ref1; 0 <= ref1 ? o++ : o--){ results.push(o); }
        return results;
      }).apply(this));
    });
    return {
      log: log,
      assert: assert,
      assertEq: assertEq,
      assertEqOn: assertEqOn,
      dict: dict,
      copy: copy,
      deepcopy: deepcopy,
      securely: securely,
      int: int,
      float: float,
      bool: bool,
      str: str,
      hex: hex,
      ord: ord,
      chr: chr,
      json: json,
      obj: obj,
      uri_encoder: uri_encoder,
      uri_decoder: uri_decoder,
      iterator: iterator,
      enumerate: enumerate,
      new_iterator: new_iterator,
      pretty_iterator: pretty_iterator,
      range: range,
      nature_number: nature_number,
      prime_number: prime_number,
      random_gen: random_gen,
      ranged_random_gen: ranged_random_gen,
      permutation_gen: permutation_gen,
      map: map,
      filter: filter,
      take: take,
      takeWhile: takeWhile,
      drop: drop,
      dropWhile: dropWhile,
      scanl: scanl,
      streak: streak,
      reverse: reverse,
      concat: concat,
      zip: zip,
      cartProd: cartProd,
      list: list,
      last: last,
      foldl: foldl,
      best: best,
      all: all,
      any: any,
      foreach: foreach,
      church: church,
      Y: Y,
      memoize: memoize,
      square: square,
      cube: cube,
      abs: abs,
      floor: floor,
      ceil: ceil,
      sum: sum,
      max: max,
      min: min,
      max_index: max_index,
      min_index: min_index,
      next_permutation: next_permutation
    };
  })();

  if (typeof window !== "undefined" && window !== null) {
    window.coffee_mate = coffee_mate;
    if (window._ == null) {
      window._ = coffee_mate;
    }
  } else {
    module.exports = coffee_mate;
  }

}).call(this);

//# sourceMappingURL=coffee_mate.js.map
