// Generated by CoffeeScript 1.9.1
(function() {
  var coffee_mate,
    slice = [].slice;

  coffee_mate = (function() {
    var Y, abs, accept_multi_or_array, all, any, assert, best, bool, cart, ceil, chr, church, concat, copy, cube, deepcopy, dict, drop, dropWhile, enumerate, filter, float, floor, foldl, foreach, function_literal, hex, int, iter_brk, iter_end, iterate, iterator, json, last, list, log, map, max, max_index, memorize, min, min_index, nature_number, new_iterator, obj, ord, prime_number, random_gen, range, ranged_random_gen, ref, securely, square, str, streak, sum, take, takeWhile, time_now, uri_decoder, uri_encoder, zip;
    function_literal = function(f) {
      var expr;
      expr = f.toString().replace(/^\s*function\s?\(\s?\)\s?{\s*return\s*([^]*?);?\s*}$/, '$1');
      if (expr.length <= 100) {
        expr = expr.replace(/[\r\n]{1,2}\s*/g, '');
      }
      return expr;
    };
    time_now = function() {
      return (new Date).getTime();
    };
    log = (function() {
      var _log, foo, histories;
      histories = [];
      foo = function(op) {
        return function() {
          var args, ball, eval_result, expr, f, l, label, len1, start_time, time_used;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          label = "#" + (op === 'log' ? '#' : op[0].toUpperCase());
          ball = [];
          for (l = 0, len1 = args.length; l < len1; l++) {
            f = args[l];
            if (typeof f === 'function') {
              expr = function_literal(f);
              start_time = time_now();
              eval_result = f();
              time_used = time_now() - start_time;
              ball.push(label + " " + expr + " ==>", f());
              if (time_used > 0) {
                ball.push("[" + time_used + "ms]");
              }
            } else {
              ball.push("" + label, f);
            }
          }
          console[op].apply(console, ball);
          histories.push(ball);
          if (histories.length >= 10) {
            histories.shift();
          }
          return null;
        };
      };
      _log = foo('log');
      _log.histories = histories;
      _log.info = foo('info');
      _log.warn = foo('warn');
      _log.error = _log.err = foo('error');
      return _log;
    })();
    assert = function(f, msg) {
      var ref;
      if (!(f instanceof Function)) {
        ref = [msg, f], f = ref[0], msg = ref[1];
      }
      if (!f()) {
        throw "Assertion Failed: " + (msg != null ? msg : function_literal(f));
      }
    };
    securely = function(f) {
      return function() {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        args = deepcopy(args);
        return f.apply(null, args);
      };
    };
    dict = function(pairs) {
      var d, k, l, len1, ref, v;
      d = {};
      for (l = 0, len1 = pairs.length; l < len1; l++) {
        ref = pairs[l], k = ref[0], v = ref[1];
        d[k] = v;
      }
      return d;
    };
    ref = (function() {
      var cp;
      cp = function(root, dep) {
        var k, r, v;
        if (dep === 0 || (root == null) || typeof root !== 'object') {
          return root;
        }
        if (root instanceof Array) {
          r = (function() {
            var l, len1, results;
            results = [];
            for (l = 0, len1 = root.length; l < len1; l++) {
              v = root[l];
              results.push(cp(v, dep - 1));
            }
            return results;
          })();
        } else {
          r = {};
          for (k in root) {
            v = root[k];
            r[k] = cp(v, dep - 1);
          }
        }
        return r;
      };
      return {
        copy: function(obj, depth) {
          if (depth == null) {
            depth = 1;
          }
          return cp(obj, depth);
        },
        deepcopy: function(obj, depth) {
          if (depth == null) {
            depth = Infinity;
          }
          return cp(obj, depth);
        }
      };
    })(), copy = ref.copy, deepcopy = ref.deepcopy;
    int = function(s, base) {
      var r;
      if (typeof s === 'string') {
        r = parseInt(s, base);
        if (!((s.slice != null) && r === parseInt(s.slice(0, -1), base))) {
          return r;
        } else {
          return null;
        }
      } else {
        return parseInt(0 + s);
      }
    };
    float = function(s) {
      if (/^-?[0-9]*(\.[0-9]+)?([eE]-?[0-9]+)?$/.test(s)) {
        return parseFloat(s);
      } else {
        return null;
      }
    };
    str = function(x, base) {
      return x.toString(base);
    };
    bool = function(x) {
      if (x === true || x === false) {
        return x;
      } else {
        return null;
      }
    };
    hex = function(x) {
      return x.toString(16);
    };
    ord = function(c) {
      return c.charCodeAt();
    };
    chr = function(x) {
      return String.fromCharCode(x);
    };
    json = function(it, indent) {
      return JSON.stringify(it, null, indent);
    };
    obj = function(s) {
      return JSON.parse(s);
    };
    Object.defineProperties(String.prototype, {
      format: {
        enumerable: false,
        value: function(args) {
          return this.replace(/\{(\w+)\}/g, function(m, i) {
            if (args[i] != null) {
              return args[i];
            } else {
              return m;
            }
          });
        }
      },
      repeat: {
        enumerable: false,
        value: function(n) {
          var pat, r, ref1;
          ref1 = ['', this], r = ref1[0], pat = ref1[1];
          while (n > 0) {
            if (n & 1) {
              r += pat;
            }
            n >>= 1;
            pat += pat;
          }
          return r;
        }
      },
      cut: {
        enumerable: false,
        value: function(start_pat, end_pat) {
          var i, j;
          i = this.search(start_pat) + 1;
          if (i === 0) {
            return null;
          }
          j = this.substr(i).search(end_pat);
          if (j === -1) {
            return null;
          }
          return this.substr(i, j);
        }
      }
    });
    Object.defineProperties(Array.prototype, {
      first: {
        get: function() {
          return this[0];
        },
        set: function(v) {
          return this[0] = v;
        }
      },
      second: {
        get: function() {
          return this[1];
        },
        set: function(v) {
          return this[1] = v;
        }
      },
      third: {
        get: function() {
          return this[2];
        },
        set: function(v) {
          return this[2] = v;
        }
      },
      last: {
        get: function() {
          return this[this.length - 1];
        },
        set: function(v) {
          return this[this.length - 1] = v;
        }
      },
      repeat: {
        enumerable: false,
        value: function(n) {
          var pat, r, ref1;
          ref1 = [[], this], r = ref1[0], pat = ref1[1];
          while (n > 0) {
            if (n & 1) {
              r = r.concat(pat);
            }
            n >>= 1;
            pat = pat.concat(pat);
          }
          return r;
        }
      },
      unique: {
        enumerable: false,
        value: (function() {
          var init;
          init = new Object;
          return function(equal) {
            var i, j, l, len1, len2, o, t, x;
            i = 0;
            t = init;
            if (equal == null) {
              for (j = l = 0, len1 = this.length; l < len1; j = ++l) {
                x = this[j];
                if (!(x !== t)) {
                  continue;
                }
                this[i] = t = x;
                i += 1;
              }
            } else {
              for (j = o = 0, len2 = this.length; o < len2; j = ++o) {
                x = this[j];
                if (!(t === init || !equal(x, t))) {
                  continue;
                }
                this[i] = t = x;
                i += 1;
              }
            }
            this.splice(i, Infinity);
            return this;
          };
        })()
      }
    });
    Object.defineProperties(Object, {
      size: {
        enumerable: false,
        value: function(d) {
          return Object.keys(d).length;
        }
      },
      extend: {
        enumerable: false,
        value: function() {
          var base, d, defaults, k, l, len1, v;
          base = arguments[0], defaults = 2 <= arguments.length ? slice.call(arguments, 1) : [];
          for (l = 0, len1 = defaults.length; l < len1; l++) {
            d = defaults[l];
            if (d != null) {
              for (k in d) {
                v = d[k];
                if (base[k] == null) {
                  base[k] = v;
                }
              }
            }
          }
          return base;
        }
      },
      update: {
        enumerable: false,
        value: function() {
          var base, d, k, l, len1, updates, v;
          base = arguments[0], updates = 2 <= arguments.length ? slice.call(arguments, 1) : [];
          for (l = 0, len1 = updates.length; l < len1; l++) {
            d = updates[l];
            if (d != null) {
              for (k in d) {
                v = d[k];
                base[k] = v;
              }
            }
          }
          return base;
        }
      }
    });
    uri_encoder = function(component_packer) {
      if (component_packer == null) {
        component_packer = str;
      }
      return function(obj) {
        var k, v;
        return ((function() {
          var results;
          results = [];
          for (k in obj) {
            v = obj[k];
            results.push((encodeURIComponent(k)) + "=" + (encodeURIComponent(component_packer(v))));
          }
          return results;
        })()).join('&');
      };
    };
    uri_decoder = function(component_unpacker) {
      if (component_unpacker == null) {
        component_unpacker = (function(s) {
          return s;
        });
      }
      return function(str) {
        var d, k, l, len1, o, ref1, ref2, ref3, s, v;
        d = {};
        ref2 = (ref1 = str.match(/[^?=&]+=[^&]*/g)) != null ? ref1 : [];
        for (l = 0, len1 = ref2.length; l < len1; l++) {
          s = ref2[l];
          ref3 = s.match(/([^=]+)=(.*)/), o = ref3.length - 2, k = ref3[o++], v = ref3[o++];
          d[decodeURIComponent(k)] = component_unpacker(decodeURIComponent(v));
        }
        return d;
      };
    };
    random_gen = (function() {
      var hash;
      hash = function(x) {
        x = Math.sin(x) * 1e4;
        return x - Math.floor(x);
      };
      return function(seed) {
        var cnt;
        if (seed == null) {
          seed = Math.random();
        }
        cnt = hash(seed);
        return function() {
          return hash(++cnt);
        };
      };
    })();
    ranged_random_gen = function(range, seed) {
      var random;
      if (seed == null) {
        seed = Math.random();
      }
      random = random_gen(seed);
      return function() {
        return Math.floor(random() * range);
      };
    };
    iter_end = new Object;
    iter_brk = new Object;
    new_iterator = function(f, show) {
      if (show == null) {
        show = (function() {
          return "Iterator";
        });
      }
      f.toString = show;
      f.next = function() {
        var r;
        r = f();
        return {
          value: r,
          done: r === iter_end
        };
      };
      return f;
    };
    nature_number = function(first) {
      var i;
      if (first == null) {
        first = 0;
      }
      i = first - 1;
      return new_iterator((function() {
        return ++i;
      }), (function() {
        return "NatureNumberIterator: " + (i + 1);
      }));
    };
    range = function() {
      var args, i, start, step, stop;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      if (args.length === 0) {
        i = -1;
        return function() {
          return ++i;
        };
      } else if (args.length === 1) {
        stop = args[0];
        i = -1;
        return function() {
          if (++i < stop) {
            return i;
          } else {
            return iter_end;
          }
        };
      } else if (args.length === 2) {
        start = args[0], stop = args[1];
        if (start < stop) {
          i = start - 1;
          return function() {
            if (++i < stop) {
              return i;
            } else {
              return iter_end;
            }
          };
        } else {
          i = start + 1;
          return function() {
            if (--i > stop) {
              return i;
            } else {
              return iter_end;
            }
          };
        }
      } else {
        start = args[0], stop = args[1], step = args[2];
        if (stop !== start && (stop - start) * step < 0) {
          throw 'ERR IN range(): YOU ARE CREATING AN UNLIMITTED RANGE';
        }
        i = start - step;
        if (start < stop) {
          return function() {
            if ((i += step) < stop) {
              return i;
            } else {
              return iter_end;
            }
          };
        } else {
          return function() {
            if ((i += step) > stop) {
              return i;
            } else {
              return iter_end;
            }
          };
        }
      }
    };
    prime_number = function() {
      return filter(function(x) {
        return all(function(p) {
          return x % p !== 0;
        })(takeWhile(function(p) {
          return p * p <= x;
        })(range(2, Infinity)));
      })(range(2, Infinity));
    };
    iterate = function(ls, replaced_end) {
      var i;
      i = -1;
      return function() {
        i += 1;
        if (i < ls.length) {
          if (ls[i] === iter_end) {
            if (replaced_end == null) {
              throw 'ERR IN iterate(): iterate.done APPEARS IN Array, PASS A SECOND ARG FOR REPLACEMENT';
            }
            return replaced_end;
          } else {
            return ls[i];
          }
        } else {
          return iter_end;
        }
      };
    };
    iterator = function(iterable, replaced_end) {
      if (typeof iterable === 'function') {
        return iterable;
      } else {
        if (!(iterable instanceof Array)) {
          throw 'ERR IN iterator(): ONLY Array & Iterator IS ACCEPTABLE';
        }
        return iterate(iterable, replaced_end);
      }
    };
    Object.defineProperties(iterator, {
      end: {
        writable: false,
        configurable: false,
        enumerable: false,
        value: iter_end
      }
    });
    enumerate = function(it, replaced_end) {
      var i, keys;
      if (typeof it !== 'function') {
        it = iterator(it);
      }
      if (typeof it === 'function') {
        return zip((function() {
          var i;
          i = -1;
          return function() {
            return ++i;
          };
        })(), it);
      } else {
        keys = Object.keys(it);
        i = -1;
        return function() {
          var k;
          if (++i < keys.length) {
            return [(k = keys[i]), it[k]];
          } else {
            return iter_end;
          }
        };
      }
    };
    take = function(n) {
      if (typeof n === 'number') {
        return function(iter) {
          var c;
          iter = iterator(iter);
          c = -1;
          return function() {
            if (++c < n) {
              return iter();
            } else {
              return iter_end;
            }
          };
        };
      } else {
        return takeWhile(n);
      }
    };
    takeWhile = function(ok) {
      return function(iter) {
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        return function() {
          var x;
          if ((x = iter()) !== iter_end && ok(x)) {
            return x;
          } else {
            return iter_end;
          }
        };
      };
    };
    drop = function(n) {
      if (typeof n === 'number') {
        return function(iter) {
          var finished, i, l, ref1;
          if (typeof iter !== 'function') {
            iter = iterator(iter);
          }
          finished = false;
          for (i = l = 0, ref1 = n; 0 <= ref1 ? l < ref1 : l > ref1; i = 0 <= ref1 ? ++l : --l) {
            finished || (finished = iter() === iter_end);
            if (finished) {
              break;
            }
          }
          if (finished) {
            return function() {
              return iter_end;
            };
          } else {
            return iter;
          }
        };
      } else {
        return dropWhile(n);
      }
    };
    dropWhile = function(ok) {
      return function(iter) {
        var x;
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        while (ok(x = iter()) && x !== iter_end) {
          null;
        }
        return function() {
          var _x, ref1;
          ref1 = [x, iter()], _x = ref1[0], x = ref1[1];
          return _x;
        };
      };
    };
    map = function(f) {
      return function(iter) {
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        return function() {
          var x;
          if ((x = iter()) !== iter_end) {
            return f(x);
          } else {
            return iter_end;
          }
        };
      };
    };
    filter = function(ok) {
      return function(iter) {
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        return function() {
          var x;
          while (!ok(x = iter()) && x !== iter_end) {
            null;
          }
          return x;
        };
      };
    };
    foldl = function(f, r) {
      return function(iter) {
        var x;
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        while ((x = iter()) !== iter_end) {
          r = f(r, x);
        }
        return r;
      };
    };
    streak = function(n) {
      return function(iter) {
        var buf;
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        buf = [];
        return function() {
          var x;
          if ((x = iter()) === iter_end) {
            return iter_end;
          }
          buf.push(x);
          if (buf.length > n) {
            buf.shift(1);
          }
          return buf.slice(0);
        };
      };
    };
    concat = function() {
      var current_index, i, iter, iters, l, len1, ref1;
      iters = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      for (i = l = 0, len1 = iters.length; l < len1; i = ++l) {
        iter = iters[i];
        if (typeof iter !== 'function') {
          iters[i] = iterator(iter);
        }
      }
      ref1 = [iters[0], 0], iter = ref1[0], current_index = ref1[1];
      return function() {
        var x;
        if ((x = iter()) !== iter_end) {
          return x;
        } else if (++current_index < iters.length) {
          iter = iters[current_index];
          return iter();
        } else {
          return iter_end;
        }
      };
    };
    zip = function() {
      var finished, i, iter, iters, l, len1;
      iters = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      for (i = l = 0, len1 = iters.length; l < len1; i = ++l) {
        iter = iters[i];
        if (typeof iter !== 'function') {
          iters[i] = iterator(iter);
        }
      }
      finished = (function() {
        var another_end, any_is_end;
        another_end = new Object;
        any_is_end = any(function(x) {
          return x === another_end;
        });
        return function(ls) {
          return any_is_end(iterator(ls, another_end));
        };
      })();
      return function() {
        var next;
        next = (function() {
          var len2, o, results;
          results = [];
          for (o = 0, len2 = iters.length; o < len2; o++) {
            iter = iters[o];
            results.push(iter());
          }
          return results;
        })();
        if (finished(next)) {
          return iter_end;
        } else {
          return next;
        }
      };
    };
    cart = (function() {
      var apply_vector, inc_vector;
      inc_vector = function(limits) {
        var len_minus_1;
        len_minus_1 = limits.length - 1;
        return function(vec) {
          var i;
          i = len_minus_1;
          while (!(++vec[i] < limits[i] || i <= 0)) {
            vec[i--] = 0;
          }
          return vec;
        };
      };
      apply_vector = function(space) {
        var len;
        len = space.length;
        return function(vec) {
          var i, l, ref1, results;
          results = [];
          for (i = l = 0, ref1 = len; 0 <= ref1 ? l < ref1 : l > ref1; i = 0 <= ref1 ? ++l : --l) {
            results.push(space[i][vec[i]]);
          }
          return results;
        };
      };
      return function() {
        var get_value, i, inc, iters, limits, set, sets, v;
        iters = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        sets = (function() {
          var l, len1, results;
          results = [];
          for (l = 0, len1 = iters.length; l < len1; l++) {
            set = iters[l];
            results.push(list(set));
          }
          return results;
        })();
        limits = (function() {
          var l, ref1, results;
          results = [];
          for (i = l = 0, ref1 = sets.length; 0 <= ref1 ? l < ref1 : l > ref1; i = 0 <= ref1 ? ++l : --l) {
            results.push(sets[i].length);
          }
          return results;
        })();
        inc = inc_vector(limits);
        get_value = apply_vector(sets);
        v = (function() {
          var l, ref1, results;
          results = [];
          for (i = l = 0, ref1 = sets.length; 0 <= ref1 ? l < ref1 : l > ref1; i = 0 <= ref1 ? ++l : --l) {
            results.push(0);
          }
          return results;
        })();
        return function() {
          var r;
          if (v[0] < limits[0]) {
            r = get_value(v);
            inc(v);
            return r;
          } else {
            return iter_end;
          }
        };
      };
    })();
    list = function(it) {
      var results, x;
      if (typeof it !== 'function') {
        return it;
      }
      results = [];
      while ((x = it()) !== iter_end) {
        results.push(x);
      }
      return results;
    };
    foreach = function(iter, callback, fruit) {
      var x;
      if (typeof iter !== 'function') {
        iter = iterator(iter);
      }
      while ((x = iter()) !== iter_end) {
        if (callback(x, fruit) === iter_brk) {
          break;
        }
      }
      return fruit;
    };
    Object.defineProperties(foreach, {
      "break": {
        writable: false,
        configurable: false,
        enumerable: false,
        value: iter_brk
      }
    });
    best = function(better) {
      return function(iter) {
        var it, r;
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        if ((r = iter()) === iter_end) {
          return null;
        }
        while ((it = iter()) !== iter_end) {
          r = better(it, r) ? it : r;
        }
        return r;
      };
    };
    all = function(f) {
      if (typeof f !== 'function') {
        f = (function(x) {
          return x === f;
        });
      }
      return function(iter) {
        var x;
        if (typeof iter !== 'function') {
          iter = iterator(iter);
        }
        while ((x = iter()) !== iter_end) {
          if (!f(x)) {
            return false;
          }
        }
        return true;
      };
    };
    any = function(f) {
      var all_not;
      all_not = all(function(x) {
        return !f(x);
      });
      return function(iter) {
        return !(all_not(iter));
      };
    };
    last = function(iter, empty_sign) {
      var r, x;
      if (typeof iter !== 'function') {
        iter = iterator(iter);
      }
      r = empty_sign;
      while ((x = iter()) !== iter_end) {
        r = x;
      }
      return r;
    };
    church = function(n) {
      var iter;
      iter = function(f, n, r) {
        if (n === 0) {
          return r;
        } else {
          return iter(f, n - 1, f(r));
        }
      };
      return function(f) {
        return function(x) {
          return iter(f, n + 0, x);
        };
      };
    };
    Y = function(f) {
      return (function(x) {
        return x(x);
      })((function(x) {
        return f((function(y) {
          return (x(x))(y);
        }));
      }));
    };
    memorize = function(f, get_key) {
      var cache;
      if (get_key == null) {
        get_key = (function() {
          var args;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          return json(args);
        });
      }
      cache = {};
      return function() {
        var args, cached, key, r;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        key = get_key.apply(null, args);
        cached = cache[key];
        if (cached != null) {
          return cached;
        } else {
          r = f.apply(null, args);
          cache[key] = r;
          return r;
        }
      };
    };
    square = function(n) {
      return n * n;
    };
    cube = function(n) {
      return n * n * n;
    };
    abs = Math.abs;
    floor = Math.floor;
    ceil = Math.ceil;
    accept_multi_or_array = function(f) {
      return function() {
        var arr;
        arr = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return f(arr.length === 1 && arr.first instanceof Array ? arr.first : arr);
      };
    };
    sum = accept_multi_or_array(function(arr) {
      var l, len1, r, x;
      if (arr.length === 1 && arr.first instanceof Array) {
        arr = arr.first;
      }
      r = 0;
      for (l = 0, len1 = arr.length; l < len1; l++) {
        x = arr[l];
        r += x;
      }
      return r;
    });
    max = accept_multi_or_array(function(arr) {
      return best(function(a, b) {
        return a > b;
      })(arr);
    });
    min = accept_multi_or_array(function(arr) {
      return best(function(a, b) {
        return a < b;
      })(arr);
    });
    max_index = accept_multi_or_array(function(arr) {
      var l, ref1, results;
      return best(function(i, j) {
        return arr[i] > arr[j];
      })((function() {
        results = [];
        for (var l = 0, ref1 = arr.length; 0 <= ref1 ? l < ref1 : l > ref1; 0 <= ref1 ? l++ : l--){ results.push(l); }
        return results;
      }).apply(this));
    });
    min_index = accept_multi_or_array(function(arr) {
      var l, ref1, results;
      return best(function(i, j) {
        return arr[i] < arr[j];
      })((function() {
        results = [];
        for (var l = 0, ref1 = arr.length; 0 <= ref1 ? l < ref1 : l > ref1; 0 <= ref1 ? l++ : l--){ results.push(l); }
        return results;
      }).apply(this));
    });
    return {
      log: log,
      assert: assert,
      dict: dict,
      copy: copy,
      deepcopy: deepcopy,
      int: int,
      float: float,
      bool: bool,
      str: str,
      hex: hex,
      ord: ord,
      chr: chr,
      json: json,
      obj: obj,
      uri_encoder: uri_encoder,
      uri_decoder: uri_decoder,
      iterator: iterator,
      enumerate: enumerate,
      range: range,
      nature_number: nature_number,
      prime_number: prime_number,
      random_gen: random_gen,
      ranged_random_gen: ranged_random_gen,
      map: map,
      filter: filter,
      take: take,
      takeWhile: takeWhile,
      drop: drop,
      dropWhile: dropWhile,
      streak: streak,
      concat: concat,
      zip: zip,
      cart: cart,
      list: list,
      last: last,
      foldl: foldl,
      best: best,
      all: all,
      any: any,
      foreach: foreach,
      church: church,
      Y: Y,
      memorize: memorize,
      square: square,
      cube: cube,
      abs: abs,
      floor: floor,
      ceil: ceil,
      sum: sum,
      max: max,
      min: min,
      max_index: max_index,
      min_index: min_index
    };
  })();

  if (typeof window !== "undefined" && window !== null) {
    window.coffee_mate = coffee_mate;
    if (window._ == null) {
      window._ = coffee_mate;
    }
  } else {
    module.exports = coffee_mate;
  }

}).call(this);

//# sourceMappingURL=coffee_mate.js.map
